"""empty message

Revision ID: c41f46f46c6b
Revises: 0bb26a7a8bc9
Create Date: 2020-03-23 21:15:52.045131

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c41f46f46c6b'
down_revision = '0bb26a7a8bc9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tweet',
    sa.Column('tweet_id', sa.Integer(), nullable=False),
    sa.Column('tweet_content', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('tweet_id')
    )
    op.create_table('user',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('user_handle', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.drop_table('book')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('book',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('title', sa.VARCHAR(length=128), nullable=True),
    sa.Column('author_id', sa.VARCHAR(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('user')
    op.drop_table('tweet')
    # ### end Alembic commands ###
